CREATE TABLE users (
  id INT GENERATED ALWAYS AS IDENTITY,
  email VARCHAR(100) NOT NULL,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  contact VARCHAR(50) NOT NULL,
  PRIMARY KEY(id)
);
